/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as storeLayoutRouteImport } from './routes/(store)/_layout'
import { Route as storeLayoutIndexRouteImport } from './routes/(store)/_layout/index'
import { Route as storeAuthSignInRouteImport } from './routes/(store)/auth/sign-in'
import { Route as storeLayoutCartRouteImport } from './routes/(store)/_layout/cart'
import { Route as storeAuthLayoutLayoutRouteImport } from './routes/(store)/auth/_layout/_layout'

const storeLayoutRoute = storeLayoutRouteImport.update({
  id: '/(store)/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const storeLayoutIndexRoute = storeLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => storeLayoutRoute,
} as any)
const storeAuthSignInRoute = storeAuthSignInRouteImport.update({
  id: '/(store)/auth/sign-in',
  path: '/auth/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const storeLayoutCartRoute = storeLayoutCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => storeLayoutRoute,
} as any)
const storeAuthLayoutLayoutRoute = storeAuthLayoutLayoutRouteImport.update({
  id: '/(store)/auth/_layout/_layout',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/cart': typeof storeLayoutCartRoute
  '/auth/sign-in': typeof storeAuthSignInRoute
  '/': typeof storeLayoutIndexRoute
  '/auth': typeof storeAuthLayoutLayoutRoute
}
export interface FileRoutesByTo {
  '/cart': typeof storeLayoutCartRoute
  '/auth/sign-in': typeof storeAuthSignInRoute
  '/': typeof storeLayoutIndexRoute
  '/auth': typeof storeAuthLayoutLayoutRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(store)/_layout': typeof storeLayoutRouteWithChildren
  '/(store)/_layout/cart': typeof storeLayoutCartRoute
  '/(store)/auth/sign-in': typeof storeAuthSignInRoute
  '/(store)/_layout/': typeof storeLayoutIndexRoute
  '/(store)/auth/_layout/_layout': typeof storeAuthLayoutLayoutRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/cart' | '/auth/sign-in' | '/' | '/auth'
  fileRoutesByTo: FileRoutesByTo
  to: '/cart' | '/auth/sign-in' | '/' | '/auth'
  id:
    | '__root__'
    | '/(store)/_layout'
    | '/(store)/_layout/cart'
    | '/(store)/auth/sign-in'
    | '/(store)/_layout/'
    | '/(store)/auth/_layout/_layout'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  storeLayoutRoute: typeof storeLayoutRouteWithChildren
  storeAuthSignInRoute: typeof storeAuthSignInRoute
  storeAuthLayoutLayoutRoute: typeof storeAuthLayoutLayoutRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(store)/_layout': {
      id: '/(store)/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof storeLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(store)/_layout/': {
      id: '/(store)/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof storeLayoutIndexRouteImport
      parentRoute: typeof storeLayoutRoute
    }
    '/(store)/auth/sign-in': {
      id: '/(store)/auth/sign-in'
      path: '/auth/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof storeAuthSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(store)/_layout/cart': {
      id: '/(store)/_layout/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof storeLayoutCartRouteImport
      parentRoute: typeof storeLayoutRoute
    }
    '/(store)/auth/_layout/_layout': {
      id: '/(store)/auth/_layout/_layout'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof storeAuthLayoutLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface storeLayoutRouteChildren {
  storeLayoutCartRoute: typeof storeLayoutCartRoute
  storeLayoutIndexRoute: typeof storeLayoutIndexRoute
}

const storeLayoutRouteChildren: storeLayoutRouteChildren = {
  storeLayoutCartRoute: storeLayoutCartRoute,
  storeLayoutIndexRoute: storeLayoutIndexRoute,
}

const storeLayoutRouteWithChildren = storeLayoutRoute._addFileChildren(
  storeLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  storeLayoutRoute: storeLayoutRouteWithChildren,
  storeAuthSignInRoute: storeAuthSignInRoute,
  storeAuthLayoutLayoutRoute: storeAuthLayoutLayoutRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
